---
- name: Configurar el servidor
  hosts: all
  vars_files:
    - main.yml
  vars:
    ansible_python_interpreter: auto_silent
  gather_facts: true
  roles:
    - { role: actualizar, become: true }
    - { role: descargar, become: true }
    - { role: instalar, become: true }
